#include "hal_servo.h"

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"

#include "servo.pio.h"   /* generated by pico_generate_pio_header */

/* --------------------------------------------------------------------------
 * Pin map (ground truth — Hardware Reference §5)
 * -------------------------------------------------------------------------- */
static const uint8_t s_pin[EVN_SERVO_COUNT] = { 2, 3, 10, 11 };

/* Servos live on pio1 (pio0 reserved for quadrature encoders — PLAN §6). */
#define SERVO_PIO pio1

typedef struct {
    int      sm;          /* state machine index, -1 if unclaimed */
    uint16_t min_us, max_us;   /* angle→µs calibration */
    uint16_t cur_us;      /* last commanded pulse */
    bool     enabled;
} servo_ch_t;

static servo_ch_t s_ch[EVN_SERVO_COUNT];
static uint s_pio_offset = 0;
static bool s_program_loaded = false;

static inline uint16_t clamp_us(uint32_t us) {
    if (us < EVN_SERVO_MIN_US) return EVN_SERVO_MIN_US;
    if (us > EVN_SERVO_MAX_US) return EVN_SERVO_MAX_US;
    return (uint16_t)us;
}

/* Push one frame (high, low) to the channel's SM. */
static void push_frame(evn_servo_id_t id, uint16_t high_us) {
    servo_ch_t *c = &s_ch[id];
    if (c->sm < 0) return;
    uint32_t low_us = EVN_SERVO_FRAME_US - high_us;
    /* non-blocking: FIFO is deep enough for several frames */
    pio_sm_put(SERVO_PIO, c->sm, high_us);
    pio_sm_put(SERVO_PIO, c->sm, low_us);
}

bool hal_servo_init(void) {
    if (!s_program_loaded) {
        s_pio_offset = pio_add_program(SERVO_PIO, &evn_servo_program);
        s_program_loaded = true;
    }

    /* clkdiv so the SM runs at 1 MHz (1 instruction = 1 µs). */
    float clkdiv = (float)clock_get_hz(clk_sys) / 1000000.0f;

    bool ok = true;
    for (int i = 0; i < EVN_SERVO_COUNT; i++) {
        int sm = pio_claim_unused_sm(SERVO_PIO, false);
        if (sm < 0) { ok = false; break; }
        s_ch[i].sm = sm;

        pio_gpio_init(SERVO_PIO, s_pin[i]);

        pio_sm_config c = evn_servo_program_get_default_config(s_pio_offset);
        sm_config_set_set_pins(&c, s_pin[i], 1);
        sm_config_set_clkdiv(&c, clkdiv);
        pio_sm_init(SERVO_PIO, sm, s_pio_offset, &c);
        /* Give the PIO output-enable on the pin, else `set pins` never drives
         * the pad (value register changes but OE stays deasserted -> no signal). */
        pio_sm_set_consecutive_pindirs(SERVO_PIO, sm, s_pin[i], 1, true);
        pio_sm_set_enabled(SERVO_PIO, sm, true);

        s_ch[i].min_us  = EVN_SERVO_DEFAULT_MIN;
        s_ch[i].max_us  = EVN_SERVO_DEFAULT_MAX;
        s_ch[i].cur_us  = EVN_SERVO_CENTER_US;
        s_ch[i].enabled = true;
        push_frame((evn_servo_id_t)i, EVN_SERVO_CENTER_US);  /* start centred */
    }
    return ok;
}

void hal_servo_write_us(evn_servo_id_t id, uint16_t pulse_us) {
    servo_ch_t *c = &s_ch[id];
    uint16_t us = clamp_us(pulse_us);
    c->cur_us = us;
    if (c->enabled) push_frame(id, us);
}

void hal_servo_write_angle(evn_servo_id_t id, float degrees, bool dir) {
    servo_ch_t *c = &s_ch[id];
    if (degrees < 0.0f)   degrees = 0.0f;
    if (degrees > 180.0f) degrees = 180.0f;
    float span = (float)(c->max_us - c->min_us);
    float us = dir ? (float)c->max_us - (degrees / 180.0f) * span
                   : (float)c->min_us + (degrees / 180.0f) * span;
    hal_servo_write_us(id, (uint16_t)us);
}

void hal_servo_set_range(evn_servo_id_t id, uint16_t min_us, uint16_t max_us) {
    s_ch[id].min_us = clamp_us(min_us);
    s_ch[id].max_us = clamp_us(max_us);
}

void hal_servo_disable(evn_servo_id_t id) {
    servo_ch_t *c = &s_ch[id];
    c->enabled = false;
    if (c->sm >= 0) {
        /* full-frame low = no pulse */
        pio_sm_put(SERVO_PIO, c->sm, 0u);
        pio_sm_put(SERVO_PIO, c->sm, EVN_SERVO_FRAME_US);
    }
}

void hal_servo_enable(evn_servo_id_t id) {
    s_ch[id].enabled = true;
    push_frame(id, s_ch[id].cur_us);
}

uint16_t hal_servo_get_us(evn_servo_id_t id) {
    return s_ch[id].cur_us;
}
