#include "hal_encoder.h"

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/gpio.h"
#include "hardware/clocks.h"

#include "quadrature.pio.h"   /* generated by pico_generate_pio_header */

/* --------------------------------------------------------------------------
 * Encoder pin/base map (ground truth — Hardware Reference §5).
 * The PIO needs consecutive A/B pins with A at the IN/JMP base. For motors
 * where B is the lower pin (M2/M4) we run the PIO from the B pin as base and
 * negate the count in software so "forward" stays consistent.
 * -------------------------------------------------------------------------- */
#define ENC_PIO pio0

typedef struct {
    uint8_t base_pin;   /* PIO IN/JMP base (A pin, or B pin when B is lower) */
    int8_t  sign;       /* +1 normal, -1 to flip direction for M2/M4 */
} enc_hw_t;

static const enc_hw_t s_hw[4] = {
    { 18, +1 },   /* M1: A=18 B=19 (base=18, normal)  */
    { 16, -1 },   /* M2: A=17 B=16 (base=16, flipped) */
    { 14, +1 },   /* M3: A=14 B=15 (base=14, normal)  */
    { 12, -1 },   /* M4: A=13 B=12 (base=12, flipped) */
};

/* Runtime count-sign overrides (default = s_hw[].sign above). */
static int8_t s_sign[4] = { +1, -1, +1, -1 };

static int      s_sm[4];
static int32_t  s_count[4];
static bool     s_loaded = false;

/* Fetch the latest step count from a SM (drain FIFO + one guaranteed-fresh
 * sample), per the official example's quadrature_encoder_get_count(). */
static int32_t fetch_count(uint sm) {
    uint32_t ret = 0;
    int n = (int)pio_sm_get_rx_fifo_level(ENC_PIO, sm) + 1;
    while (n-- > 0) {
        ret = pio_sm_get_blocking(ENC_PIO, sm);
    }
    return (int32_t)ret;
}

bool hal_encoder_init(void) {
    if (!s_loaded) {
        /* MUST load at origin 0 (program uses computed jumps / jump table). */
        uint off = pio_add_program_at_offset(ENC_PIO, &evn_quad_program, 0);
        if (off != 0) return false;
        s_loaded = true;
    }

    for (int i = 0; i < 4; i++) {
        int sm = pio_claim_unused_sm(ENC_PIO, false);
        if (sm < 0) return false;
        s_sm[i] = sm;
        s_count[i] = 0;

        uint pin = s_hw[i].base_pin;
        pio_sm_set_consecutive_pindirs(ENC_PIO, sm, pin, 2, false);
        pio_gpio_init(ENC_PIO, pin);
        pio_gpio_init(ENC_PIO, pin + 1);
        gpio_pull_up(pin);
        gpio_pull_up(pin + 1);

        pio_sm_config c = evn_quad_program_get_default_config(0);
        sm_config_set_in_pins(&c, pin);
        sm_config_set_jmp_pin(&c, pin);
        sm_config_set_in_shift(&c, false, false, 32);   /* shift left, no autopull */
        sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_NONE);
        sm_config_set_clkdiv(&c, 1.0f);                  /* full sysclk */

        pio_sm_init(ENC_PIO, sm, 0, &c);
        pio_sm_set_enabled(ENC_PIO, sm, true);
    }
    return true;
}

void hal_encoder_service(void) {
    for (int i = 0; i < 4; i++) {
        /* The PIO keeps an absolute count in Y. We take the delta vs the last
         * fetched raw value and apply the per-motor sign. */
        static int32_t last_raw[4] = {0, 0, 0, 0};
        int32_t raw = fetch_count(s_sm[i]);
        int32_t delta = raw - last_raw[i];
        last_raw[i] = raw;
        s_count[i] += delta * s_sign[i];
    }
}

int32_t hal_encoder_get_count(evn_encoder_id_t id) {
    return s_count[id];
}

void hal_encoder_reset(evn_encoder_id_t id) {
    s_count[id] = 0;
}

void hal_encoder_set_sign(evn_encoder_id_t id, int8_t sign) {
    s_sign[id] = (sign < 0) ? -1 : +1;
}
